spring.application.name=gateway
server.port=8080
server.address=0.0.0.0
services.usuarios=http://127.0.0.1:8081
services.board=http://127.0.0.1:8082
jwt.secret=${JWT_SECRET:chave-academica-tadswitter-mudar-na-apresentacao-2026}
