spring.application.name=usuarios-api
server.port=8081
server.address=127.0.0.1
spring.datasource.url=jdbc:h2:file:./dados/usuarios
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
